### ISSUE TITLE
Problem to open camera in android sdk

### ISSUE THREAD

**Issue by quickdrowing** [itsdlhqcp/AYUR_LAEF#5]
In converting flask app to android app with web view:-
->I converted it into webview - This app require two resources from mobile device 1. Upload image from device storage, 2 open camera to take photo
->I implemented upload image with some pieces of code
->But not able to use camera in webview😖

**Comment by itsdlhqcp** [comment]
With android studio converting to Web app , you have little or no control to change anything, This days there are even website that can give you apk  out of url ,once you submit the url ::->
1. https://www.webtonative.com/?utm_source=GA&utm_id=14533622626&utm_medium=CPC&utm_campaign=international&gad_source=1&gclid=Cj0KCQiAsvWrBhC0ARIsAO4E6f8OOuwB_9y5wNhuRyWO_EGfFKg41TqVjRp9b8Vy1O9DEvnORiq5tf8aAgENEALw_wcB
2.  https://www.freewebsitetoapp.com/convert-website-to-app-for-free/ 

I hope those two website will help you convert your Web app into app

**Comment by quickdrowing** [comment]
> With android studio converting to Web app , you have little or no control to change anything, This days there are even website that can give you apk out of url ,once you submit the url ::->
> 
> 1. https://www.webtonative.com/?utm_source=GA&utm_id=14533622626&utm_medium=CPC&utm_campaign=international&gad_source=1&gclid=Cj0KCQiAsvWrBhC0ARIsAO4E6f8OOuwB_9y5wNhuRyWO_EGfFKg41TqVjRp9b8Vy1O9DEvnORiq5tf8aAgENEALw_wcB
> 2. https://www.freewebsitetoapp.com/convert-website-to-app-for-free/
> 
> I hope those two website will help you convert your Web app into app
